// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Code along with the Foundation Models framework in Xcode",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "Code along with the Foundation Models framework in Xcode",
            targets: ["AppModule"],
            bundleIdentifier: "suppppppp.Code-along-with-the-Foundation-Models-framework-in-Xcode",
            teamIdentifier: "Q83JD2ZC9T",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ],
    swiftLanguageVersions: [.version("6")]
)